"""initial_schema

Revision ID: b9b5aa122ba1
Revises: 
Create Date: 2026-04-06 19:32:44.200567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9b5aa122ba1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_code')
    )
    op.create_table('dim_cost_centers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cost_center_code', sa.String(length=50), nullable=False),
    sa.Column('cost_center_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cost_center_code')
    )
    op.create_table('dim_date',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('is_weekend', sa.Integer(), nullable=False),
    sa.Column('is_holiday', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('dim_vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_code', sa.String(length=50), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_code')
    )
    op.create_table('fact_forecast_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cost_center_id', sa.Integer(), nullable=True),
    sa.Column('ds', sa.Date(), nullable=False),
    sa.Column('yhat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('yhat_lower', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('yhat_upper', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('model_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cost_center_id'], ['dim_cost_centers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ds', 'cost_center_id', 'model_version', name='uix_forecast_ds_cc_version', postgresql_nulls_not_distinct=True)
    )
    op.create_table('fact_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('cost_center_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['dim_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cost_center_id'], ['dim_cost_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_date'], ['dim_date.date'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vendor_id'], ['dim_vendors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', name='uix_external_id')
    )
    op.create_table('anomaly_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('anomaly_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_anomaly', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['fact_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_results')
    op.drop_table('fact_transactions')
    op.drop_table('fact_forecast_results')
    op.drop_table('dim_vendors')
    op.drop_table('dim_date')
    op.drop_table('dim_cost_centers')
    op.drop_table('dim_accounts')
    # ### end Alembic commands ###
